#############################################################################
# Makefile for building: UI_v2
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sat May 4 15:51:48 2013
# Project:  UI_v2.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.4/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile UI_v2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DECLARATIVE_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.4/include/QtCore -I/usr/local/Trolltech/Qt-4.8.4/include/QtGui -I/usr/local/Trolltech/Qt-4.8.4/include/QtDeclarative -I/usr/local/Trolltech/Qt-4.8.4/include -Iqmlapplicationviewer -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.4/lib -lQtDeclarative -L/usr/local/Trolltech/Qt-4.8.4/lib -lQtScript -lQtSvg -L/usr/X11R6/lib -lQtSql -lQtXmlPatterns -lQtNetwork -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		CAN_Setup.cpp \
		AC_Controls.cpp \
		Radio_HeadUnit.cpp \
		CanRecieve.cpp \
		CanControl.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_qmlapplicationviewer.cpp \
		moc_CAN_Setup.cpp \
		moc_AC_Controls.cpp \
		moc_Radio_HeadUnit.cpp \
		moc_CanRecieve.cpp \
		moc_CanControl.cpp \
		qrc_UI_Pictures.cpp
OBJECTS       = main.o \
		CAN_Setup.o \
		AC_Controls.o \
		Radio_HeadUnit.o \
		CanRecieve.o \
		CanControl.o \
		qmlapplicationviewer.o \
		moc_qmlapplicationviewer.o \
		moc_CAN_Setup.o \
		moc_AC_Controls.o \
		moc_Radio_HeadUnit.o \
		moc_CanRecieve.o \
		moc_CanControl.o \
		qrc_UI_Pictures.o
DIST          = /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		UI_v2.pro
QMAKE_TARGET  = UI_v2
DESTDIR       = 
TARGET        = UI_v2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: UI_v2.pro  /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtDeclarative.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtScript.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtSvg.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtSql.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtXmlPatterns.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile UI_v2.pro
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/declarative_debug.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtDeclarative.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtScript.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtSvg.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtSql.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtXmlPatterns.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile UI_v2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/UI_v21.0.0 || $(MKDIR) .tmp/UI_v21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/UI_v21.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h CAN_Setup.h AC_Controls.h Radio_HeadUnit.h CanRecieve.h CanControl.h .tmp/UI_v21.0.0/ && $(COPY_FILE) --parents UI_Pictures.qrc .tmp/UI_v21.0.0/ && $(COPY_FILE) --parents main.cpp CAN_Setup.cpp AC_Controls.cpp Radio_HeadUnit.cpp CanRecieve.cpp CanControl.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/UI_v21.0.0/ && (cd `dirname .tmp/UI_v21.0.0` && $(TAR) UI_v21.0.0.tar UI_v21.0.0 && $(COMPRESS) UI_v21.0.0.tar) && $(MOVE) `dirname .tmp/UI_v21.0.0`/UI_v21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/UI_v21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qmlapplicationviewer.cpp moc_CAN_Setup.cpp moc_AC_Controls.cpp moc_Radio_HeadUnit.cpp moc_CanRecieve.cpp moc_CanControl.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlapplicationviewer.cpp moc_CAN_Setup.cpp moc_AC_Controls.cpp moc_Radio_HeadUnit.cpp moc_CanRecieve.cpp moc_CanControl.cpp
moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

moc_CAN_Setup.cpp: CAN_Setup.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CAN_Setup.h -o moc_CAN_Setup.cpp

moc_AC_Controls.cpp: AC_Controls.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) AC_Controls.h -o moc_AC_Controls.cpp

moc_Radio_HeadUnit.cpp: Radio_HeadUnit.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) Radio_HeadUnit.h -o moc_Radio_HeadUnit.cpp

moc_CanRecieve.cpp: CanRecieve.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CanRecieve.h -o moc_CanRecieve.cpp

moc_CanControl.cpp: CanRecieve.h \
		CanControl.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CanControl.h -o moc_CanControl.cpp

compiler_rcc_make_all: qrc_UI_Pictures.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_UI_Pictures.cpp
qrc_UI_Pictures.cpp: UI_Pictures.qrc \
		qml/UI_v2/UIPictures/print3.png \
		qml/UI_v2/UIPictures/print7.png \
		qml/UI_v2/UIPictures/actemp2.png \
		qml/UI_v2/UIPictures/battPage.png \
		qml/UI_v2/UIPictures/AM.png \
		qml/UI_v2/UIPictures/volumeBar.png \
		qml/UI_v2/UIPictures/actemp1.png \
		qml/UI_v2/UIPictures/print4.png \
		qml/UI_v2/UIPictures/radioPage.png \
		qml/UI_v2/UIPictures/volSetting.png \
		qml/UI_v2/UIPictures/acDown.png \
		qml/UI_v2/UIPictures/acPage.png \
		qml/UI_v2/UIPictures/energyPage.png \
		qml/UI_v2/UIPictures/print1.png \
		qml/UI_v2/UIPictures/print5.png \
		qml/UI_v2/UIPictures/acUp.png \
		qml/UI_v2/UIPictures/acWindow.png \
		qml/UI_v2/UIPictures/acCirculate.png \
		qml/UI_v2/UIPictures/FM.png \
		qml/UI_v2/UIPictures/radioOff.png \
		qml/UI_v2/UIPictures/radioOn.png \
		qml/UI_v2/UIPictures/print2.png \
		qml/UI_v2/UIPictures/acIcon.png \
		qml/UI_v2/UIPictures/print6.png \
		qml/UI_v2/UIPictures/acLeft.png \
		qml/UI_v2/UIPictures/dockPage.png
	/usr/local/Trolltech/Qt-4.8.4/bin/rcc -name UI_Pictures UI_Pictures.qrc -o qrc_UI_Pictures.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp CAN_Setup.h \
		AC_Controls.h \
		Radio_HeadUnit.h \
		CanControl.h \
		CanRecieve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

CAN_Setup.o: CAN_Setup.cpp CAN_Setup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CAN_Setup.o CAN_Setup.cpp

AC_Controls.o: AC_Controls.cpp AC_Controls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AC_Controls.o AC_Controls.cpp

Radio_HeadUnit.o: Radio_HeadUnit.cpp Radio_HeadUnit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Radio_HeadUnit.o Radio_HeadUnit.cpp

CanRecieve.o: CanRecieve.cpp CanRecieve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanRecieve.o CanRecieve.cpp

CanControl.o: CanControl.cpp CanControl.h \
		CanRecieve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanControl.o CanControl.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

moc_CAN_Setup.o: moc_CAN_Setup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CAN_Setup.o moc_CAN_Setup.cpp

moc_AC_Controls.o: moc_AC_Controls.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AC_Controls.o moc_AC_Controls.cpp

moc_Radio_HeadUnit.o: moc_Radio_HeadUnit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Radio_HeadUnit.o moc_Radio_HeadUnit.cpp

moc_CanRecieve.o: moc_CanRecieve.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CanRecieve.o moc_CanRecieve.cpp

moc_CanControl.o: moc_CanControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CanControl.o moc_CanControl.cpp

qrc_UI_Pictures.o: qrc_UI_Pictures.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_UI_Pictures.o qrc_UI_Pictures.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/UI_v2/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/UI_v2/qml/ 
	-$(INSTALL_DIR) /home/lucid/Dropbox/UI_v2/qml/UI_v2 $(INSTALL_ROOT)/opt/UI_v2/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/UI_v2/qml/UI_v2
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/UI_v2/qml/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/UI_v2/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/UI_v2/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/UI_v2/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/UI_v2/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/UI_v2/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

